<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'CCU2',
  'author' => '',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'CCU2',
  'published_date' => '2016-04-26 13:33:31',
  'type' => 'module',
  'version' => 1461677611,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'CCU2',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'CCU2_Agents2',
      'class' => 'CCU2_Agents2',
      'path' => 'modules/CCU2_Agents2/CCU2_Agents2.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'CCU2_Agents3',
      'class' => 'CCU2_Agents3',
      'path' => 'modules/CCU2_Agents3/CCU2_Agents3.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'CCU2_Logins',
      'class' => 'CCU2_Logins',
      'path' => 'modules/CCU2_Logins/CCU2_Logins.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'CCU2_agent_docs',
      'class' => 'CCU2_agent_docs',
      'path' => 'modules/CCU2_agent_docs/CCU2_agent_docs.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ccu2_agents3_notes_CCU2_Agents3.php',
      'to_module' => 'CCU2_Agents3',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ccu2_logins_ccu2_agents3_CCU2_Agents3.php',
      'to_module' => 'CCU2_Agents3',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/ccu2_agent_docs_ccu2_agents3_CCU2_Agents3.php',
      'to_module' => 'CCU2_Agents3',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ccu2_agents3_notesMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ccu2_logins_ccu2_agents3MetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/ccu2_agent_docs_ccu2_agents3MetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/CCU2_Agents2',
      'to' => 'modules/CCU2_Agents2',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/CCU2_Agents3',
      'to' => 'modules/CCU2_Agents3',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/CCU2_Logins',
      'to' => 'modules/CCU2_Logins',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/CCU2_agent_docs',
      'to' => 'modules/CCU2_agent_docs',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/Notes.php',
      'to_module' => 'Notes',
      'language' => 'ru_ru',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CCU2_Agents3.php',
      'to_module' => 'CCU2_Agents3',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CCU2_Agents3.php',
      'to_module' => 'CCU2_Agents3',
      'language' => 'ru_ru',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CCU2_Logins.php',
      'to_module' => 'CCU2_Logins',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CCU2_Logins.php',
      'to_module' => 'CCU2_Logins',
      'language' => 'ru_ru',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CCU2_Agents3.php',
      'to_module' => 'CCU2_Agents3',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CCU2_Agents3.php',
      'to_module' => 'CCU2_Agents3',
      'language' => 'ru_ru',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CCU2_agent_docs.php',
      'to_module' => 'CCU2_agent_docs',
      'language' => 'en_us',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CCU2_agent_docs.php',
      'to_module' => 'CCU2_agent_docs',
      'language' => 'ru_ru',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CCU2_Agents3.php',
      'to_module' => 'CCU2_Agents3',
      'language' => 'en_us',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/CCU2_Agents3.php',
      'to_module' => 'CCU2_Agents3',
      'language' => 'ru_ru',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/ru_ru.lang.php',
      'to_module' => 'application',
      'language' => 'ru_ru',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ccu2_agents3_notes_Notes.php',
      'to_module' => 'Notes',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ccu2_agents3_notes_CCU2_Agents3.php',
      'to_module' => 'CCU2_Agents3',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ccu2_logins_ccu2_agents3_CCU2_Logins.php',
      'to_module' => 'CCU2_Logins',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ccu2_logins_ccu2_agents3_CCU2_Agents3.php',
      'to_module' => 'CCU2_Agents3',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ccu2_agent_docs_ccu2_agents3_CCU2_agent_docs.php',
      'to_module' => 'CCU2_agent_docs',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/ccu2_agent_docs_ccu2_agents3_CCU2_Agents3.php',
      'to_module' => 'CCU2_Agents3',
    ),
  ),
  'layoutfields' => 
  array (
    0 => 
    array (
      'additional_fields' => 
      array (
        'Notes' => 'ccu2_agents3_notes_name',
      ),
    ),
    1 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
    2 => 
    array (
      'additional_fields' => 
      array (
      ),
    ),
  ),
);